[project]
name = "challenge-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "hiddenlayer>=0.3",
    "ipykernel>=7.2.0",
    "kagglehub>=1.0.0",
    "matplotlib>=3.10.8",
    "numpy>=2.4.4",
    "pandas>=3.0.2",
    "path>=17.1.1",
    "pillow>=12.2.0",
    "poethepoet>=0.44.0",
    "polars>=1.40.0",
    "python-dotenv>=1.2.2",
    "torch>=2.11.0",
    "torchinfo>=1.8.0",
    "torchview>=0.2.7",
    "torchvision>=0.26.0",
]
